allowBuilds:
  '@ast-grep/lang-angular': true
  '@ast-grep/lang-bash': true
  '@ast-grep/lang-bicep': true
  '@ast-grep/lang-c': true
  '@ast-grep/lang-cpp': true
  '@ast-grep/lang-csharp': true
  '@ast-grep/lang-css': true
  '@ast-grep/lang-dart': true
  '@ast-grep/lang-elixir': true
  '@ast-grep/lang-glimmer-javascript': true
  '@ast-grep/lang-glimmer-typescript': true
  '@ast-grep/lang-go': true
  '@ast-grep/lang-haskell': true
  '@ast-grep/lang-html': true
  '@ast-grep/lang-java': true
  '@ast-grep/lang-javascript': true
  '@ast-grep/lang-json': true
  '@ast-grep/lang-kotlin': true
  '@ast-grep/lang-lua': true
  '@ast-grep/lang-markdown': true
  '@ast-grep/lang-php': true
  '@ast-grep/lang-python': true
  '@ast-grep/lang-ruby': true
  '@ast-grep/lang-rust': true
  '@ast-grep/lang-scala': true
  '@ast-grep/lang-sql': true
  '@ast-grep/lang-swift': true
  '@ast-grep/lang-toml': true
  '@ast-grep/lang-tsx': true
  '@ast-grep/lang-typescript': true
  '@ast-grep/lang-yaml': true
